# Generated by Django 4.1.7 on 2023-03-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='News',
        ),
    ]
