# Generated by Django 4.1.7 on 2023-03-17 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_events_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.CharField(max_length=100000000)),
                ('Room', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Room',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='value',
        ),
    ]
